import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import morgan from 'morgan';
import { env } from './config/env.js';
import { authRouter } from './routes/auth.js';
import { transactionRouter } from './routes/transactions.js';
import { dashboardRouter } from './routes/dashboard.js';
import { exportRouter } from './routes/exports.js';
import { requireAuth } from './middleware/auth.js';
import { errorHandler } from './middleware/error.js';

export const app = express();
app.use(helmet()); app.use(cors({ origin: env.FRONTEND_URL, credentials: true })); app.use(express.json({ limit: '1mb' })); app.use(cookieParser()); app.use(morgan('dev'));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', authRouter);
app.use('/api/transactions', requireAuth, transactionRouter);
app.use('/api/dashboard', requireAuth, dashboardRouter);
app.use('/api/exports', requireAuth, exportRouter);
app.use((_req, res) => res.status(404).json({ message: 'Route not found' }));
app.use(errorHandler);
